labels: ["Proposals"]
body:
  - type: markdown
    attributes:
      value: |
        # New Proposal

        Please follow the template below. 
        
        The more details you can add the better the chances this proposal will get accepted.
       
  - type: input
    id: has-id
    attributes:
      label: What is it about?
      description: In one sentence, what's the summary of the proposal (ignore if it's the same as the title) 

  - type: textarea
    id: motivation
    attributes:
      label: What's the motivation for this proposal?
      description: please describe the problems / goals
      value: |
        
        ## Problems you are trying to solve:
        * 
        * 

        ## Goals you are trying to achieve:
        * 
        * 
        
        ## Any other context or information you want to share:

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution / Feature
      description: Please describe the solution you have in mind. Include code examples if relevant.
      
        
        
  - type: textarea
    id: reference
    attributes:
      label: Links / References
      description: Please include reference links if there are any
     
            